name: Backfill NSE Bhavcopy (90d)

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: prices-backfill
  cancel-in-progress: true

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Backfill many days, rebuild 90d, and EQ shards
        run: python tools/build_prices.py --backfill 150
      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "prices-bot"
            git config user.email "prices-bot@users.noreply.github.com"
            git add -A
            git commit -m "backfill: daily+90d+EQ shards $(date -u +%F)"
            git push
          else
            echo "No changes to commit."
          fi
