name: Backfill Prices

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Backfill + 90d + EQ shards
        run: python tools/build_prices.py --backfill 150
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: backfill: daily+90d+EQ shards
          commit_user_name: prices-bot
          commit_user_email: prices-bot@users.noreply.github.com
