name: Fetch NSE PIT (30d)

on:
  schedule:
    - cron: "10 4 * * *"    # ~09:40 IST
  workflow_dispatch:

# Prevent two runs from racing each other
concurrency:
  group: pit-fetch-main
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0                 # full history, avoids push rejects
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm i
          npx playwright install --with-deps chromium

      - name: Run Playwright fetcher
        run: node scripts/pit_fetch.js

      # --- Git config & sync with remote before committing ---
      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config pull.rebase true

      - name: Pull latest (rebase) to avoid non-fast-forward
        run: |
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }} || true

      - name: Commit CSVs
        run: |
          git add -A data/*.csv
          git commit -m "PIT update" || echo "No changes"
          git push origin ${{ github.ref_name }}
