name: Fetch NSE PIT (30d)

permissions:
  contents: write

concurrency:
  group: iss-data-updates
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # get full history so rebase works
          ref: main             # adjust if your default branch isn't main
          persist-credentials: true

      # ... your steps that fetch/build CSVs go here ...

      - name: Commit CSVs if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # exit if nothing changed
          if git diff --quiet; then
            echo "No changes — skipping push."
            exit 0
          fi

          git add -A
          git commit -m "Data update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # rebase onto latest main and push (retry a couple of times if racing another run)
          for attempt in 1 2 3; do
            git pull --rebase origin main || true
            if git push origin HEAD:main; then
              echo "Pushed on attempt ${attempt}"
              break
            fi
            echo "Push failed; retrying..."
            sleep 3
          done
