name: Prices Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '15 14 * * 1-5'

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build daily + 90d + EQ shards
        run: python tools/build_prices.py --days 10
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: mirror: daily+90d+EQ shards
          commit_user_name: prices-bot
          commit_user_email: prices-bot@users.noreply.github.com
