name: Prices Mirror (NSE Bhavcopy)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 14 * * 1-5'  # ~19:45 IST Mon–Fri

permissions:
  contents: write

concurrency:
  group: prices-fetch
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build latest daily, 90d, and EQ shards
        run: python tools/build_prices.py --days 10
      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "prices-bot"
            git config user.email "prices-bot@users.noreply.github.com"
            git add -A
            git commit -m "mirror: daily+90d+EQ shards $(date -u +%F)"
            git push
          else
            echo "No changes to commit."
          fi
