name: Prices Mirror (NSE Bhavcopy)

on:
  workflow_dispatch:
  schedule:
    - cron: '5 15 * * 1-5'
    - cron: '5 16 * * 1-5'
    - cron: '5 17 * * 1-5'

permissions:
  contents: write

concurrency:
  group: prices-fetch
  cancel-in-progress: false

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest available bhavcopy (tries last 5 calendar days)
        run: bash scripts/fetch_prices.sh

      - name: Show fetched files (debug)
        run: |
          echo "::group::Listing data/prices"
          ls -la data/prices || true
          echo "::endgroup::"

      - name: Commit changes (if any)
        run: |
          set -e
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Stage everything first (includes untracked files)
          git add -A

          # Commit only if there is something staged
          if git diff --cached --quiet; then
            echo "No price updates to commit."
          else
            git commit -m "chore(prices): mirror bhavcopy via workflow $GITHUB_RUN_ID"
            git push
          fi
